### ISSUE TITLE
Outlier Detection in rapidminer

### ISSUE THREAD

**Issue by ishratjahan** [Markus-Go/rapidminer-anomalydetection#3]
I am doing a comparative study of outlier algorithms. For that I need to generate ROC Curves.
For generate ROC operator in rapidminer, I need to provide a  label. What label should I provide agter applying outlier detection algorithms

**Comment by Markus-Go** [comment]
Hello,

Thanks for using my extension for your experiments.
For plotting ROC curves, you need to provide the ground truth labels of your data. The algorithms typically don't need it, since they are unsupervised, but for performance comparison you need a labeled dataset.

Make sure, if you import your dataset, that it has a column with the role "label". Here, only 2 values should occur (for normal and outlier). In the ROC operator, you then need to specify the value of this column in the parameter settings. For example, if your label is "o" for outliers and "n" for normal data, just write "o" in the ROC settings.

The ROC is then automatically determined by varying a threshold over the outlier scores (a standard procedure).

If you need some standard labeled datasets, I recently published a few, which I used for a comparative study in a journal article. You can find them here: http://dx.doi.org/10.7910/DVN/OPQMVF

**Comment by yilmazerhan** [comment]
Hi Markus,
First of all thanks for great tools for anomaly detection. 

I have achieved to get ROC and AUC results. But it is only for 1 algorithm. I need to duplicate Generate ROC operator for each algorithm. Is it possible to combine all ROC result into a single plot for comparison?

Best regards

**Comment by Markus-Go** [comment]
This is not possible in RM; However, simply export the ROC (see output of operator) and use any other tool to plot multiple ROCs in one plot.
